### ISSUE TITLE
give proper error message if unshare(2) fails

### ISSUE THREAD

**Issue by stevenrbrandt** [hpc/charliecloud#103]
I'm not sure what I'm doing wrong or if it can be fixed.

$ /project/containers/charliecloud/bin/ch-run --no-home -vv stevenrbrandt/phylanx.release/latest -- /bin/bash
newroot: /ddnA/project/sbrandt/chemora/stevenrbrandt/phylanx.release/latest
container uid: 1168
container gid: 10000
private /tmp: 0
setup_namespaces 518: uids=1168,1168,1168, gids=10000,10000,10000 + 1028,10000,10001,10010
ch-run: error: Invalid argument (ch-run.c:519 22)

$ uname -a
Linux shelob1 2.6.32-696.10.3.el6.x86_64 #1 SMP Thu Sep 21 12:12:50 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wiene** [comment]
@stevenrbrandt, looking at your kernel version it seems that your kernel is too old to support user namespaces (it requires version 3.8 or newer; for more info see [this LWN article](https://lwn.net/Articles/532593)).

**Comment by wiene** [comment]
Also note that even if your kernel was sufficiently new, your Linux distribution might have switched off user namespaces by default. This is e. g. the case for RHEL/CentOS 7.4 and Debian 9. The [Charliecloud documentation](https://hpc.github.io/charliecloud/install.html#run-time) explains how to switch them on.

**Comment by reidpr** [comment]
@wiene is correct on the underlying cause. Another workaround you can try is to compile in setuid mode; this should work on RHEL/CentOS 6.

However, the error message is unnecessarily opaque. We can fix that.

What you're seeing is the default error message when we think the problem is unlikely to be encountered by users; this assessment seems clearly wrong here. Anyway, what you have is:

* program that failed (here `ch-run`)
* "error"
* `strerror(3)` representation of `errno` (here "Invalid argument")
* file and line number where the problem was noticed (here `ch-run.c`, line 519)
* `errno` (here 22, i.e. `EINVAL`)

You get `EINVAL` because `clone(CLONE_NEWUSER)` (i.e., user namespaces) is not supported in 2.6.32.

**Comment by trandles-lanl** [comment]
I'll +1 this bug report.  I spent quite a bit of time figuring out what command line option I had passed in error to ch-run, when the issue was actually user namespaces not being enabled.  I hadn't passed an invalid argument, ch-run had passed an invalid argument to unshare() on my behalf. ;)
