### ISSUE TITLE
ch-image build --force: support CentOS Stream

### ISSUE THREAD

**Issue by sbiae5** [hpc/charliecloud#1095]
With the death of centos8 are there any plans to support centos stream with ch-image build --force ?
Or is the recommendation to stick to centos 7 ?

**Comment by reidpr** [comment]
Thanks for the request! Let us look into it.

**Comment by heasterday** [comment]
As a note, it doesn't appear that there are official CentOS Stream images on Dockhub but I was able to test with [this Dockerfile](https://github.com/tgagor/docker-centos-stream/blob/master/Dockerfile).

Looks like the issue is that our current regex match expects the version string to be of the form "x." but CentOS Stream only has a major version. I will whip up a PR to relax our regex to allow matching.

**Comment by sbiae5** [comment]
We have been pulling the stream from quay.io (quay.io/centos/centos:stream8) rather than going back to centos7. If the regex can be updated that would be handy, I did have a quick look at changing it but trying to keep as close to source as possible so students can replicate it easily in future. Thanks

**Comment by heasterday** [comment]
@sbiae5 Could you give the `1095-support-centos-stream` branch a try and see if it works for you?

**Comment by sbiae5** [comment]
All working perfectly so far, thanks for the quick response.
Have just tested with the basics but seems to be working the same as centos8 so should be good.
