### ISSUE TITLE
`ch-image --force`: support Arch

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#1295]

**Comment by reidpr** [comment]
PR #1276 introduces an attempt at this that is currently commented out.

**Comment by loveshack** [comment]
I found an Arch-colleague to consult, but I found another problem beforehand.

I didn't find a dbus-1 package in arch, but I saw the same sort of thing with dbus, which doesn't happen with simple things, and rather looks as if it's due to expecting a running system.

The other one is from installing Emacs as a test, since it sucks in all sorts.  That produces output like this (and more that's similar).  It looks as if it's trying to run binaries from the image with the host glibc for some reason -- presumably another case of symlinks that I'll try to debug when I have time.

```
:: Running post-transaction hooks...
( 1/13) Creating system user accounts...
Creating group 'avahi' with GID 975.
Creating user 'avahi' (Avahi mDNS/DNS-SD daemon) with UID 975 and GID 975.
( 2/13) Reloading system manager configuration...
Failed to check for chroot() environment: Permission denied
  Skipped: Current root is not booted.
( 3/13) Arming ConditionNeedsUpdate...
( 4/13) Updating the MIME type database...
/usr/bin/update-mime-database: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/libxml2.so.2)
error: command failed to execute correctly
( 5/13) Updating fontconfig configuration...
( 6/13) Reloading system bus configuration...
Failed to check for chroot() environment: Permission denied
  Skipped: Current root is not booted.
( 7/13) Updating fontconfig cache...
( 8/13) Probing GDK-Pixbuf loader modules...
g_module_open() failed for /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-avif.so: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/libSvtAv1Enc.so.0)
```

**Comment by loveshack** [comment]
The glibc problem is actually due to there not being proper dependency management on dynamic libraries.  glibc in the pulled image is older than the one fakeroot was built against. I'll send a change to fix that.

I haven't tried yet to figure out why there are those fchownat errors from dbus (it's intercepted by fakeroot), but are they actually a problem?  Is dbus expected to work in the container?

**Comment by reidpr** [comment]
Does the environment variable in PR #1362 fix this?

**Comment by loveshack** [comment]
> Does the environment variable in PR #1362 fix this?

Yes.  See the PR posted to enable it and Alpine.
