### ISSUE TITLE
ch-run: can't init user+mount namespaces: Operation not permitted (ch-run.c:519 1)

### ISSUE THREAD

**Issue by hstern2** [hpc/charliecloud#133]
I'm trying to run a charliecloud image on RHEL 7.4 
I think user ns should be enabled, 
CONFIG_USER_NS=y and

/proc/sys/user/max_user_namespaces is set to 10000

but I get

ch-run: can't init user+mount namespaces: Operation not permitted (ch-run.c:519 1)

any suggestions?

**Comment by reidpr** [comment]
@hstern2, did this solve your problem?

**Comment by hstern2** [comment]
yes thank you!

**Comment by reidpr** [comment]
Great! Glad we could help you.

**Comment by dongli** [comment]
I have tested both cases with or without `namespace.unpriv_enable=1`, it looks that does not matter if `CONFIG_USER_NS=y`. You just need to set `user.max_user_namespaces` to a nonzero value. Any idea?

**Comment by wiene** [comment]
Since RHEL/CentOS 7.6 user mount namespaces are fully supported (see the [release announcement](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/7.6_release_notes/index#new_features_kernel)). I think the kernel boot parameter is not needed anymore since this release.
