### ISSUE TITLE
`ch-test`: glibc version errors on Ubuntu 22.04

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#1430]

**Comment by lucaudill** [comment]
Looks like this is caused by an [incompatibility](https://news.ycombinator.com/item?id=32479545) between glibc 2.34 and older versions. It appears that Ubuntu is packaged with newer versions of glibc (in my case, 2.35), whereas the container this test is trying to run uses 2.28. The solution in the PR above (#1497) is to skip the test if the host and guest glibc versions are incompatible.

**Comment by lucaudill** [comment]
oops
