### ISSUE TITLE
style: lower-case variables in shell scripts

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#145]
Currently the shell scripts use upper-case variable names. This is poor style because it can clash with variables used by the shell (and I have already run into this issue). Thus, change the variable names to lower case.

E.g., see: https://unix.stackexchange.com/questions/42847

**Comment by mej** [comment]
Just as a warning, I've seen exactly the opposite -- lowercase variable name use conflicting with shell variables.  `csh` and derivatives use lowercase internal variables.

I'll just say a few things on this:
- Variables you export to the environment should always be uppercase.
- Uppercase variable names make the code easier to read because shell keywords and command names are almost always lowercase.  In the absence of colored syntax highlighting, lowercase variable names intermixed with lowercase everything else makes the code extremely difficult to sight-read.
- The best practice for preventing variable name conflicts, particularly in shell scripts/tools, is always the same:  Namespace them.  Pick a prefix, like `CC_` or `CHC_`, and stick with it.  That's one of the big mistakes I made early on with NHC that I'm now stuck with -- not namespacing my variables.
- Also, properly declare and scope variables via `declare`/`typeset`, `local`, and `readonly`, and only export the ones you must.

**Comment by reidpr** [comment]
> Just as a warning, I've seen exactly the opposite -- lowercase variable name use conflicting with shell variables. csh and derivatives use lowercase internal variables.

I spent a little bit of time on Google just now trying to see if there's a consensus on the matter. The above appears to be a minority view; e.g.:

* https://unix.stackexchange.com/questions/42847
* https://stackoverflow.com/questions/673055
* https://google.github.io/styleguide/shell.xml#Naming_Conventions
* http://wiki.bash-hackers.org/scripting/style#variable_names

all support the lowercase convention. I couldn't find anything supporting the upper-case convention.

What have I missed?

> * Variables you export to the environment should always be uppercase.

Agreed.

>  * Uppercase variable names make the code easier to read because shell keywords and command names are almost always lowercase. In the absence of colored syntax highlighting,

I'm a little skeptical of this argument because it seems to me that the situations where one needs to read shell code in the absence of syntax coloring should be somewhat unusual (e.g., don't we have `vim` or `emacs` pretty much everywhere.

Also, wouldn't this apply to every scripting language, e.g. Perl and Python too?

> * The best practice for preventing variable name conflicts, particularly in shell scripts/tools, is always the same: Namespace them. Pick a prefix, like CC_ or CHC_, and stick with it. That's one of the big mistakes I made early on with NHC that I'm now stuck with -- not namespacing my variables.

I'm concerned about the level of visual noise this would introduce.

> * Also, properly declare and scope variables via declare/typeset, local, and readonly, and only export the ones you must.

I agree. See issue #222.
