### ISSUE TITLE
Building documentation fails with Sphinx 1.4.9

### ISSUE THREAD

**Issue by wiene** [hpc/charliecloud#151]
Running `make` in `doc-src` yields the following error:
```
/path/to/charliecloud/doc-src$ make
[...]
Warning, treated as error:
/path/to/charliecloud/doc-src/faq.rst:None: WARNING: nonlocal image URI found: https://media.giphy.com/media/1mNBTj3g4jRCg/giphy.gif

Makefile:56: recipe for target 'html' failed
make: *** [html] Error 1
```
The problem is caused by [this commit](https://github.com/hpc/charliecloud/commit/13d4b8bb87a5b02e3ed82209977a1c787bed21da).

It might be useful to add a unit test to check whether the documentation builds without problems.

**Comment by reidpr** [comment]
> It might be useful to add a unit test to check whether the documentation builds without problems.

We do have such a test; it's in `make test-build`, and unless something is broken, it's in the Travis CI test suite.

I can't reproduce the issue with Sphinx version 1.7.1. What version of Sphinx do you have?

**Comment by wiene** [comment]
I am using the version shipped with Debian stretch (1.4.9).

**Comment by reidpr** [comment]
OK, thanks!

1.7.1 is pretty new. Do the docs build OK for you aside from that non-local image?

The README claims that 1.7.1+ is required, but that's only because I don't really know what earlier versions would work and the cost/benefit of supporting a given version.

Being able to support the stock Sphinx in Debian Stretch would seem to be of significant benefit IMO.

Our theme, `sphinx-rtd-theme`, does not appear to state a Sphinx version dependency.

**Comment by reidpr** [comment]
OK, thank you! I'll get rid of the image or figure out how to make it work on 1.4.9.

**Comment by reidpr** [comment]
@wiene, will you please test and re-open if it still doesn't work?

**Comment by wiene** [comment]
@reidpr, I successfully tested your patch on Stretch. Thanks!
