### ISSUE TITLE
Investigate img as an alternative to Docker for image builds

### ISSUE THREAD

**Issue by mej** [hpc/charliecloud#154]
See:  https://github.com/genuinetools/img

Offers daemonless, OCI-compatible container builds from `Dockerfile` source.

**Comment by reidpr** [comment]
`img` does not currently implement `export`, only `save`.

**Comment by reidpr** [comment]
@paulbry has been analyzing img and gave a nice presentation today. Some notes:

1. img prefers to use overlayfs, but overlayfs with unprivileged user namespaces is a Ubuntuism and not allowed in upstream kernels (as of 4.9).
2. The alternative is to simply copy everything for each new layer, which consumes a lot of space and time. The specific performance impact would need to be tested.
    * Possible img patch: use hard links for the unchanged stuff.
3. img uses the `newuidmap(1)` and `newgidmap(1)` utilities, which need configuration and are just wrappers to write the files in `/proc`.
    * Possible img patch: write the files directly.
4. img does not support `export`, just `save`. Charliecloud needs the former. Paul has a prototype flattener in Python, and @mej has Bash code for it.
    * Paul will submit a feature request.
5. Is there value in pursuing img for just `push` and `pull`, without `build`? (See also #41.)
6. img uses [runc](https://github.com/opencontainers/runc) to accomplish the `RUN` steps in the Dockerfile. While runc isn't as heavyweight as Docker, it's still an entire second container implementation.
    * Possible img patch: Write a `config.json` interpreter for Charliecloud and use that.
    * Possible img patch: Use ccon instead of runc, which may be lighter weight.

**Comment by AkihiroSuda** [comment]
> The alternative is to simply copy everything for each new layer, which consumes a lot of space and time. 

On xfs and btrfs, reflink could be used for saving the space.
Also, starting with kernel 4.18, we will be able to use FUSE unionfs implementations as well, although implementing unionfs-like filesystem is very bug-prone. 

> Possible img patch: use hard links for the unchanged stuff.

Not sure how this is possible, because you can't predict the set of the files that are going to be changed before running the actual `RUN` steps.

> img uses the newuidmap(1) and newgidmap(1) utilities, which need configuration and are just wrappers to write the files in /proc. Possible img patch: write the files directly.

No, you can't set up multi-user `/proc/self/[ug]id_map` without using these SUID binaries.
A workaround would be to use Ptrace and Xattr for emulating multi-user in userspace, although it is extremely slow unless we can somehow implement seccomp accelerator in a reliable way. https://github.com/rootless-containers/runrootless


> img does not support export, just save. 

`img unpack` is almost equivalent to `docker export`

> Is there value in pursuing img for just push and pull, without build?

I suggest using skopeo.

**Comment by reidpr** [comment]
I think we are going down the Buildah path, so closing.
