### ISSUE TITLE
build cache mixes Git versions

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#1606]
Some systems have `/var/tmp -> /tmp`. In this case, when using the default storage path of `/var/tmp`, you can hit errors with the build cache.

```
$ ch-image pull --arch=ppc64le --tls-no-verify nvcr.io/nvidia/cuda:11.8.0-devel-ubi8
[...]
environment: {'GIT_DIR': '/var/tmp/sly1.ch/img/nvcr.io%nvidia%cuda+11.8.0-devel-ubi8/ch/git', 'GIT_WORK_TREE': '/var/tmp/sly1.ch/img/nvcr.io%nvidia%cuda+11.8.0-devel-ubi8'}
fatal: Not a git repository: /tmp/sly1.ch/bucache/worktrees/nvcr.io%nvidia%cuda+11.8.0-devel-ubi8
error: command failed with code 128: git add -A
```

perhaps set CH_IMAGE_STORAGE to the deferenced path, in this case, `/tmp`, to avoid issue?

**Comment by j-ogas** [comment]
Hmm, it appears there may be more to this issue. The issue is happening after changing the storage location.

```
$ export CH_IMAGE_STORAGE=/tmp/sly1.ch
$ ch-image reset
[...]
$ ch-image pull --tls-no-verify nvcr.io/nvidia/cuda:11.8.0-devel-ubi8
[...]
image arch: ppc64le
gathered file metadata in 0.908s
executing: git add -A
environment: {'GIT_DIR': '/tmp/sly1.ch/img/nvcr.io%nvidia%cuda+11.8.0-devel-ubi8/ch/git', 'GIT_WORK_TREE': '/tmp/sly1.ch/img/nvcr.io%nvidia%cuda+11.8.0-devel-ubi8'}
fatal: Not a git repository: /tmp/sly1.ch/bucache/worktrees/nvcr.io%nvidia%cuda+11.8.0-devel-ubi8
error: command failed with code 128: git add -A
```

I'm unable to reproduce. I've asked the user for the full verbose log.

**Comment by reidpr** [comment]
Update from user:

> Same error after a `ch-image reset` and `ch-image pull alpine:latest`.  It pull just fine, it just doesn't set up the git "repository" before trying to run `git add -A`

```
executing: git add -A
environment: {'GIT_DIR': '/tmp/USER.debug/img/alpine+latest/ch/git', 'GIT_WORK_TREE': '/tmp/USER.debug/img/alpine+latest'}
fatal: Not a git repository: /tmp/USER.debug/bucache/worktrees/alpine+latest
error: command failed with code 128: git add -A
```

**Comment by reidpr** [comment]
So this turned out to have a fascinating cause.

On the Charliecloud side, PR #1576 moved the Git data out of band (#1285) using a couple of Git environment variables. Our bug was that we used these as Git’s *complete* environment, rather than extending the existing environment. In particular, `PATH` was removed, so finding executables fell back to the default path, which seems to vary but does include `/usr/bin`.

Along with this error, Git’s architecture involves a lot of subprocesses. I think this means that `git` is re-executed, *using `PATH`*, so if the Git in use is not the system Git (i.e., installed somewhere other than `/usr/bin/git`), then mixed versions of Git are used.

That is, I think what happens is that (a) Python finds the `git` the user wanted using `PATH`, but then (b) some subprocesses use `/usr/bin/git`. If that Git understands worktrees, then there is no visible symptom; if not, then it fails with the error message above. (E.g., this bug was identified on RHEL7, where the system Git is version 1.8.)
