### ISSUE TITLE
Add `seccomp` support for s390x architecture

### ISSUE THREAD

**Issue by wiene** [hpc/charliecloud#1772]
As per #1279 Charliecloud uses AlmaLinux 8 based images for testing purposes. s390x is the only supported AlmaLinux 8 architecture without `seccomp` support in Charliecloud (cf. #1771). Therefore, I think, it would be nice to expand `seccomp` coverage to that architecture.

**Comment by reidpr** [comment]
@wiene, would you have the bandwidth to submit a PR to do this? I believe all that’s needed is to extend `SECCOMP_ARCHS` and `FAKE_SYSCALL_NRS` in `ch_core.c`. The needed syscall numbers are listed by [`strace`](https://github.com/strace/strace/blob/v6.6/src/linux/s390x/syscallent.h).

We can do these things but I hesitate because we don’t have access to any s390x hardware.
