### ISSUE TITLE
upgrade examples to OpenMPI 3.1

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#226]

**Comment by hppritcha** [comment]
see for example the hello world example in
https://github.com/hpc/charliecloud/tree/master/examples/mpi/mpihello

**Comment by hppritcha** [comment]
@heasterday and @hppritcha worked on this today and ran into severe turbulence owing to changes in the way Open MPI starting with the 3.0.x series checks whether or not to initialize its PMIx framework.  Starting with this series (see commit open-mpi/ompi@011403c04a7368f7266e6b6da27e41f28b49f502) there's some "helpful" checking within the binary whether or not the user is trying to launch the process(es) using mpirun (aka orte) or some other launcher (srun or alps).  This "helpful" checking requires the --with-slurm=no NOT be set in order for it to be able to detect that the job is being used with SLURM and so can try and use SLURMs PMI2 or PMI1.  This is irrespective of whether or not --with-pmi was requested.  

Now there are several ways around this 
- open a PR against Open MPI to undo some of the effects of the above mentioned commit.  However I very much doubt the author of that commit will accept such changes as he'd say why are you asking for SLURM pmi support but then disabling use of SLURM itself.
- maintain a patch (small and only to configury and not source code itself) which would be applied as part of building Open MPI for the container
- use an addition mca parameter on the ```mpirun``` command line when running mpirun within the container (the use case that hit turbulence without using the --with-slurm=no configure option).

Hunter is testing a patched Open MPI with the configury change and also the additional mca parameter option.

**Comment by reidpr** [comment]
Thanks for the detective work. Couple ideas I had:

1. Remove Slurm stuff at a finer grain via `configure --enable-mca-no-build`.
2. Document Slurm environment variable to unset if you are doing guest launch.

**Comment by hppritcha** [comment]
hmm... okay for 1. then we'd remove ```--with-slurm=no``` and add in ```--enable-mca-no-build=plm-slurm``` to disable using slurmd based launch of the orted(s) when doing guest based launch.  If this works,  there should be no need to do 2 which is gross.

**Comment by reidpr** [comment]
Closed by PR #272, commit 3c371c8. Forgot to close in commit message.

**Comment by reidpr** [comment]
Re-opening; all or most of the MPI tests fail on OPA clusters, and perhaps other multi-node environments. Errors include:

```
$ srun -n2 ch-run /var/tmp/mpihello -- /hello/hello
[fg003:93760:0:93760]    ud_iface.c:300  Assertion `qp_init_attr.cap.max_inline_data >= UCT_UD_MIN_INLINE' failed
```

```
   ORTE was unable to reliably start one or more daemons.
```

```
   [fg003.localdomain:147902] OPAL ERROR: Not initialized in file pmix2x_client.c at line 109
   --------------------------------------------------------------------------
   The application appears to have been direct launched using "srun",
```

I think the best way to proceed is to create a new branch from master, re-apply `3c371c8` in the branch, fix the problems, and submit a new PR.

**Comment by heasterday** [comment]
Update on this issue, there are two separate scenarios with different issues. First there is the host launch case where mpirun/srun is used to start up instances of charliecloud containers which then launch the application. The issue in this case is the inclusion of ucx within the container which means when the tests are ran on a cluster with OPA present you bump into the following issue:
https://github.com/openucx/ucx/issues/750
There are a couple routes on this one (in no particular order): 

The Openmpi UCX pml plugin could be edited to, in the presence of HFI devices, throw a message and defer to some other available pml. This would create issues in the case where there are 
Infiniband and OPA devices on the same node (how common is this?).

The -mca pml ^ucx flag (or corresponding env variable) could be used within the launch to exclude it from consideration. 

Someone could add some logic to UCX itself to prevent it from attempting to use HFI devices if it detects them.

Moving on to guest launches (where mpirun is called within the container):
The issue is that now the example container is built with Slurm's ras plugin (Resource Allocation Subsystems) which makes it aware of other nodes within the allocation. This means within a multi-node allocation openmpi will try and do some startup stuff on remote nodes and guest launches will fail. There are a couple routes on this:

The addition of the flag --host localhost will resolve the main case but is not applicable for a serial launch (where an mpi application is launched directly without mpirun)

Dropping all Slurm environment variables on guest launch per https://github.com/hpc/charliecloud/issues/295 which would resolve all instances of guest launches which I have tested.

Apologies for the length of this.
