### ISSUE TITLE
fix "guest starts ranks" tests on Crays - MPICH

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#255]
We're getting a bunch of independent rank-0 processes again.

**Comment by heasterday** [comment]
I'm currently only seeing this behavior (independent rank-0 processes) after ch-fromhost --cray-mpi is called, guest launches with the original MPICH 3.2.1 libmpi (not cray-ified) don't appear to exhibit this behavior. Interestingly there are also process managment issues for OpenMPI 3.1.3 after overriding its libmpi on the crays. 

Towards that end I would like to propose we only use ch-fromhost --cray-mpi when host launch via srun is required, not prior to guest launches. In the case of guest launches this would preserve the MPI install in its original state and also not tie it to the libmpi of the host. For the case of guest launches I don't see any pressing need for anything from the MPI installs on the host since it is single node anyway. Guest launches would still require the unsetting of certain Slurm environment variables in the case of MPICH and OpenMPI.

I would like to get some thoughts from the team on this.

**Comment by reidpr** [comment]
Discussed at today's meeting.

* We are going to split this into two issues because the MPICH and OpenMPI problems are different. #380 is for OpenMPI.

* Why does MPICH not work? Does it help to use Cray's `mpirun` instead of the open source one?

* The proposed fix (don't `--cray-mpi` for guest launch) would introduce a subtle ordering issue into the test suite. This may be another argument to get rid of `ch-fromhost`.
