### ISSUE TITLE
CH_BIN and LIBEXEC in scripts

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#259]
The variables `CH_BIN` and `LIBEXEC` in shell scripts are upper case. To follow up #145, it seems to me that they should also be converted to lower case?

**Comment by j-ogas** [comment]
These two particular variables were skipped due to ShellCheck [SC2154](https://github.com/koalaman/shellcheck/wiki/SC2154).  

`bin/ch-build` and `bin/ch-fromhost`both use a non-local variable (`ch_bin`) declared in `bin/bash.sh`. Shellcheck SC2154 flags this as an error because it cannot detect that the variable has been assigned. 

Possible solutions: 1) We can disable this directive with `-e SC2154` or 2) check if the variable is assigned at runtime (or fail) with `${ch_bin:?}`. FWIIW, I prefer the latter.
