### ISSUE TITLE
chrun_file in charliecloud.c is sometimes missing a null terminator

### ISSUE THREAD

**Issue by j-ogas** [hpc/charliecloud#315]
The following flavor of error is sometimes seen because the `chrun_file` string is not properly assigned a null terminator:

```
   ch-run[48984]: can't bind: not found: /home/charlie/charliecloud/0.9.5/bin/ch-run�/ch-ssh (charliecloud.c:117)
```

**Comment by reidpr** [comment]
The issue here is that `readlink(3)` does not terminate the string it returns; from the [man page](http://man7.org/linux/man-pages/man2/readlink.2.html):

> `readlink()` places the contents of the symbolic link *pathname* in the buffer *buf*, which has size *bufsiz*.  `readlink()` does not append a null byte to *buf*. It will (silently) truncate the contents (to a length of *bufsiz* characters), in case the buffer is too small to hold all of the contents.

My erroneous reading of this was that a string-terminating zero byte was not provided only in the case where the buffer was too small. In fact, the zero byte is never provided.

We're puzzled why this did not come up more often; the erroneous code has been present for a long time and only now started failing tests on a single cluster. Apparently, *buf* was almost always zeroed to start, so the string was usually terminated by luck.
