### ISSUE TITLE
Software defined networking and Charlie cloud integration

### ISSUE THREAD

**Issue by PrathameshTugaonkar** [hpc/charliecloud#327]
How to integrate SDN and Charliecloud for HPC?

**Comment by reidpr** [comment]
Hello Prathamesh,

The general philosophy of Charliecloud is to do one thing well, specifically run containers. So dealing with software-defined networking would be out of scope. Because Charliecloud uses the host network stack unchanged, any SDN on the host would pass through to the container.

But maybe I am missing something. Can you say more about your use case?

Thanks,
Reid

**Comment by reidpr** [comment]
I'm going to close this issue to keep things tidy, but please re-open if you'd like to pursue it further. Thanks!
