### ISSUE TITLE
Zip files and tarballs downloaded from GitHub don't build or pass tests

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#33]
This is for two reasons:

1. GitHub doesn't include submodules when it makes those `.zip`s, so Bats is missing.

2. `VERSION.full` is missing and can't be built because it's not a Git checkout.

Expected behavior: After unpacking, the `.zip` files build (`make` at top level) and pass tests (`cd test && make test`).

**Comment by reidpr** [comment]
Possible workaround: Attach `.tar.gz` files we build with `make export` to releases using the web interface. But, this is kind of clunky and only solves part of the problem.

**Comment by reidpr** [comment]
OK, here are a couple of options:

**Option A: Manually publish tarballs**

1. Add to the release process: `make export` a tarball and attach it to the release in GitHub.

2. Document that GitHub zip files don't work, and why. (AFAICT we can't disable the zip downloads.)

Advantages:

* Version numbers always contain the Git commit & are the same no matter how the software was obtained.
* No extra steps required to run tests.

Disadvantages:

* Releases are more complex.
* Still offer zip files that don't work.
* Working tarballs only available for released versions.
* Harder to use a separate Bats install.

**Option B: Accept trade-offs to make GitHub zip files work**

1. Change the Makefile to build `VERSION.full` as simply a copy of `VERSION` if not in a Git checkout. This would lose some information (Git commit) but make the software buildable.

2. Change the tests to pick up `bats` from `$PATH`, add `test/bats.src/bin` to `$PATH`, and remove `test/bats` symlink. This will let the tests use either a separately installed Bats (e.g., Bats is in Debian already and could be a `Suggests:` or `Recommends:`) or one installed into the Charliecloud source code.

3. Document that Bats is needed to run tests, and how to get it. 

4. Remove `make export` target.

Advantages:

* Zip files from GitHub now work.
* Duplicate install of Bats no longer needed if it's already available.
* Complex `make export` code goes away.

Disadvantages:

* `ch-run --version` etc. can report different things for the same commit depending on how it was obtained.
* Running tests needs extra steps.

Opinions?

**Comment by olifre** [comment]
Since `bats` is also already in CentOS7 and Gentoo, I think I would favour Option B, the major reasons being the reduced work to release, and since that seems to be the only way to actually make the GitHub zips work (I also don't think they can be turned off). Also, the added extra steps to run the tests only need to be done once (and one could even add a new make target `bootstrap-bats` which does the "local installation" of bats inside the Charliecloud tree). 

The disadvantage of `ch-run --version` becoming less informative is probably not such a huge issue - most people will use either releases or the git checkout, I hope. 
Any other ways to obtain the source from git without the git checkout will at least contain a version-string like `0.2.3~pre` which emphasizes that it is based on something not released yet, and a user reporting an issue with a `pre` version without git hash should be able to specify how it was obtained. 

So even though I think it's more work now, option B will pay off in the long run, and the disadvantages seem acceptable. 

Let's see what others think ;-).
