### ISSUE TITLE
filesystem permission enforcement tests fail

### ISSUE THREAD

**Issue by mcv21** [hpc/charliecloud#35]
Hi,

I've built charliecloud on Debian stable (a couple of small patches forthcoming), but I can't get the filesystem permissions enforcement tests to work. The failure is:
```
 ✗ filesystem permission enforcement
   (in test file run_uidgid.bats, line 58)
     `ch-run -t $UID_ARGS $GID_ARGS -b $d $CHTEST_IMG -- \' failed
   no ID arguments
   
   verifying: /home/debian/cctest/perms_test/pass
   d /mnt/0/ld.out-a~---      rwt mismatch
   f /mnt/0/lf.out-a~---      rw- mismatch
   RISK 2 mismatches in 2887 tests
```
This is on a debian stable system (a VM inside openstack), running as the user `debian`, using current master charliecloud. Any suggestions, please?

**Comment by mcv21** [comment]
FTR, I have `CH_TEST_PERMDIRS=/home/debian/cctest /tmp` set, and ran the command from the docs `for d in $CH_TEST_PERMDIRS; do sudo ./make-perms-test $d $USER nobody; done`

**Comment by reidpr** [comment]
@mcv21, thanks for all the thoughtful feedback! These issues and PRs are very much appreciated.

I have meetings all day so it might take me a little while to respond substantively to each one.

**Comment by reidpr** [comment]
I think the trick here is that those two symlinks should be broken because they point outside the bind-mounted directory, but because your home directory is bind-mounted in by default, they're not broken.

In the report, the last three characters of the filename are the expected access, and the actual access is before "mismatch".

In terms of what to do, we could change the test (in `run_uidgid.bats`) to add `--no-home`, which should make the above configuration work. I'll do this now. Can you try again and re-open the issue if the problem persists?

**Comment by mcv21** [comment]
That's fixed the problem, thanks! `make test-run` now passes everything (except for 3 skipped tests - the setuid-mode test, and two 'missing' tests)
