### ISSUE TITLE
official package of charliecloud in openSUSE Tumbleweed

### ISSUE THREAD

**Issue by ana** [hpc/charliecloud#404]
Just a quick comment to announce I have added charliecloud to openSUSE Tumbleweed:
https://software.opensuse.org/package/charliecloud
And we're looking now into a future addition to SUSE Linux Enterprise.

**Comment by reidpr** [comment]
Thanks @ana! That's great to hear!

Would it be appropriate to update the packaging section of our docs? If so, you could submit a PR or just let us know what content to add. https://hpc.github.io/charliecloud/install.html#package-manager-install

Also, we are working on Fedora/EPEL RPMs that we would maintain. Maybe there is some opportunity for collaboration? Or, if you prefer to host your openSUSE packages within the Charliecloud source code, we could do that & figure out what level of commit access is needed.

**Comment by ana** [comment]
Hi @reidpr, I'll send a PR to update the docs.
With respect the collaboration with the Fedora/EPEL RPMs, let me take a look next week!

**Comment by ana** [comment]
Hello, a small update on this.

charliecloud is going to be include in SUSE Linux Enterprise via https://packagehub.suse.com/ . I'm waiting for the package to be accepted in packagehub to add a PR updated the documentation.

I've checked the current spec file for Fedora. I'm not sure it's worth it maintaining the spec file in git here because in openSUSE we use the  OpenSUSE Build Service and it's easier for an interested user, to branch our package there https://build.opensuse.org/package/show/network:cluster/charliecloud , edit their changes and have it automatically build for openSUSE.
I could create a PR with the instructions on how to do this to be included under a openSUSE/ directory.
What do you think?

**Comment by reidpr** [comment]
Hello @ana,

Thanks for the update.

Yes, we'd like a PR with instructions. Appreciate the offer. Where exactly they would go isn't clear to me yet; I think the options are either (1) `doc-src/install.rst` or (2) that file plus more details in the contributors' guide or a text file. But you could submit a PR with them going wherever and we can clean it up.

That said, I do wonder about collaborating more closely on the SUSE package. For example we do ship the tests, which we feel are important because there are quite a lot of corner cases that we run into and it's important for users to be able to thoroughly exercise things. More generally, I'd like to understand better why our spec files look different and make sure anything important in one finds its way into the other.

We are working on getting our RPMs into Fedora and also plan to submit them to OpenHPC (where it is currently unmaintained).

If you like, we'd love for you to call into one of our meetings to discuss by voice. I don't know where you are located, but we can surely find a time that works OK for everyone.

**Comment by j-ogas** [comment]
> More generally, I'd like to understand better why our spec files look different and make sure anything important in one finds its way into the other.

Agreed. @ana, note that the spec file in `packaging/fedora/charliecloud/spec` is not up to date. For comparison, please refer to this [copr build](https://copr-be.cloud.fedoraproject.org/results/jogas/charliecloud/fedora-rawhide-x86_64/00896310-charliecloud/) for the most recent iteration.

Also, we do have some changes on the horizon with 0.9.10, e.g., our source tarballs will include pre-built html files, which will be remove the need to build them.

**Comment by ana** [comment]
@reidpr Good idea, discussing by voice will make things easier. I'm sending you a mail directly so we can find a time slot.
