### ISSUE TITLE
test suite: add Lustre ioctl test(s)

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#406]
Some apps like to make Lustre ioctl calls on Lustre directories bind-mounted into the container. Does this work? Let's test it to see.

Not sure whether installing the Lustre utilities or making the ioctl calls directly in a toy app would be better.

**Comment by Brofessional** [comment]
Sending Lustre ioctls does appear to work from inside a container.

I was able to run `lfs getstripe` and `lfs setstripe` from within the container on a bind mounted Lustre share.

Some notes:
Lustre can be built inside a container from source
The container must be writable, the `lfs` command appears to write some things in order to perform the work.

It could be taken a step further to make a script that manually calls the ioctls, but that seemed like more work than just building Lustre in a container and testing common commands.

We could add these tests to the suite, but I'm not sure how we would go about skipping them if testing on a machine with no Lustre.

**Comment by Brofessional** [comment]
I managed to prune the Lustre client image to about 1GB in Docker and 320MB on disk after exporting to squashfs. 
I know it's been a while since we talked about it but I would like to make a case for using the C API or LFS.
I spent a lot of time looking at the Lustre code and such to try and figure out sending IOCTLs manually. 
1) You would need a set of cracked header files that would allow you to import them as the ones in Lustre won't allow it without modification. 
2) You would need to spend a lot of time figuring out the rather complex data types being sent through IOCTLs to make a test with meaningful results. Simply sending trash IOCTLs doesn't have any value. It turns out that sending IOCTLs to a distributed filesystem is complicated. There's a lot of legwork in knowing how to send an IOCTL that will do anything useful and not corrupt data or anything. 
3) The barrier to entry for the C API or LFS is rather low and can be easily scripted in a way that we can perform meaningful tests.
4) Sending IOCTLs all willy nilly can be dangerous, which is why Lustre doesn't want you doing it. Small mistakes can have big consequences.

I think sending IOCTLs is more work, less reliable, less meaningful, and silly when Lustre provides ways to interact with Lustre as intended.

**Comment by reidpr** [comment]
Good arguments. How hard is it to do an image including the C API but not the LFS utilities?

**Comment by Brofessional** [comment]
That could be possible if you build from source, but is unlikely. Installing via RPM installs them both. You could just dumpster the LFS command line binary in the image.

**Comment by Brofessional** [comment]
How should we decide whether or not we run Lustre tests? The user would have to provide a lustre space where they have read and write to bind mount in. Maybe we could add yet another environment variable? `CH_LUSTRE=/path/to/lustre`
I am open to smarter and or higher effort solutions.

**Comment by reidpr** [comment]
I'd add a `--lustre=/foo/bar` or similar option to `ch-test`.
