### ISSUE TITLE
update test suite to prefer squashfs workflow

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#441]
Currently, the test suite uses mostly a `.tar.gz` workflow, with other formats having separate individual tests. This issue changes to mostly a SquashFS workflow.

**Comment by Brofessional** [comment]
In order to switch between a tar workflow or squashfs workflow for BATS tests some adjustments need to be made.

We must know at build time which workflow to target.
Some tests that are involved in make-auto require a tarball later down the line, some do not.
make-auto will need some of the following changes:

1. Extra templates added for squahsfs
2. Current templates modified to work for either workflow
3. Possibly some of both 1 and 2 to make sure tests that require a tarball will have a tarball

Furthermore, make-auto uses chunky python strings that span multiple lines which must be smushed to the left to avoid spacing in the scripts it produces. I would like to have some mechanism to avoid this.

1. A helper function to reduce the extra indentation, so these strings can be tabbed in to match the current indent level
2. Move the template strings to files that are read in at run time. This would shorten the overall length of make-auto and improve readability.

**Comment by Brofessional** [comment]
Today it was decided:

Move template strings into template files such that:
`charliecloud/test/make-auto.d/run-image.bats`
is the format to be followed.

Templates will be modified to work with either a tar or a squash when possible.

**Comment by reidpr** [comment]
I think we can revive this. I think the basic logic is:

1. Update `make-auto.d/unpack.bats.in` to `ch-mount` the squashes.
2. Add a fourth phase (e.g.) `cleanup` after `examples` that uses a new template file `make-auto.d/cleanup.bats.in` to `ch-unmount` them, or no-op in the case of tarballs.
3. Make sure that Travis is mostly squash-enabled but has one test with no squashfuse and one test with no squash at all.

Any tests that need to modify the images should be enumerated. Once we know the magnitude of the problem, we can figure out what to do about them.

**Comment by reidpr** [comment]
I think this is done; closing as moot.
