### ISSUE TITLE
can't deduce Sphinx Python on Gentoo, maybe others

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#629]
@olifre pointed out in comments on PR #624:

> [T]his PR broke the build on Gentoo Linux (and potentially others). 
The problem is that:
> ```
> sphinx_python=$(head -1 "$SPHINX" | sed -E 's/^..//')
> ```
> does not work. On Gentoo, any python tool which is installed with multiple implementations is wrappered:
> ```
> $ ls -la $(which sphinx-build)
> lrwxrwxrwx 1 root root 31  4. Jan 18:44 /usr/bin/sphinx-build -> ../lib/python-exec/python-exec2
> $ head /usr/lib/python-exec/python-exec2
> #!/usr/bin/python-exec2c
> # vim:fileencoding=utf-8:ft=python
> # (c) 2012-2016 Michał Górny
> # Released under the terms of the 2-clause BSD license.
> #
> # This is not the script you are looking for. This is just a wrapper.
> # The actual scripts of this application were installed
> # in subdirectories of /usr/lib/python-exec.
> # You are most likely looking for one of those.
> ```
> This is done so the system can runtime-switch implementation (like Debian's `update- alternatives`). 
> More details at:
> https://wiki.gentoo.org/wiki/Project:Python/python-exec
>
> I'm not sure about the best way to work around this here, at least checking the first line of `sphinx-build` is not portable enough. 

and also:

> Maybe the "easiest" would be to have a flag to force the assumption that the `sphinx_python` is the same as the system's `python`?

**Comment by reidpr** [comment]
@olifre, would it work to provide a `configure` option `--with-sphinx-python` that takes the path to the proper Python interpreter?

**Comment by olifre** [comment]
@reidpr This would work. By design, on Gentoo, an implementation is chosen at runtime (can be chosen system-wide, but also by the user, or even switched via environment variable). This only works for packages installed for the appropriate target, otherwise a fallback is made. 
Of course, at build-time, the implementation which is used is known, so I can pass the used interpreter as argument to {{configure}} without a problem. By design, it will always be the same implementation used for the other build steps (package dependencies ensure that sphinx and themes are build against the same implementation(s)). So that sounds like a good solution!
