### ISSUE TITLE
Charliecloud dependency gpgme for Spack

### ISSUE THREAD

**Issue by audreystott** [hpc/charliecloud#635]
Hi guys, I posted a Charliecloud-related issue [here](https://github.com/spack/spack/issues/14605) but was wondering if you guys have come across this problem too seeing as it is a dependency of Charliecloud for Spack? Thanks!

**Comment by j-ogas** [comment]
@audreystott Thanks for taking time to bring attention to this issue here and on Spack. Hopefully it will be addressed soon.

If you need an immediate workaround you could try the kludge in PR #636 (i.e., force spack to use the system gpg), and include `^python+libxml2` for the builder, e.g., `spack install charliecloud+builder ^python+libxml2`.

**Comment by audreystott** [comment]
Thanks for the swift response Jordan, what a clever and easy fix!

**Comment by reidpr** [comment]
With the merge of PR #616, we are no longer using skopeo to pull images. Was that the reason for the dependency? Is this issue now moot?

**Comment by j-ogas** [comment]
This issue is now obsolete! Closing.
