### ISSUE TITLE
"make dist" tarballs are missing some things

### ISSUE THREAD

**Issue by wiene** [hpc/charliecloud#662]
It seems that `bin/ch-tar2squash` is missing in [this charliecloud-0.13.tar.gz tarball](https://github.com/hpc/charliecloud/releases/download/v0.13/charliecloud-0.13.tar.gz) although it is available in [this tarball](https://github.com/hpc/charliecloud/archive/v0.13.tar.gz) and in the tag `v0.13`. I also see more differences between those tarballs.

**Comment by reidpr** [comment]
Thanks for the report! We'll fix it.

**Comment by reidpr** [comment]
General note: @wiene, @trophime, @olifre, and any others I missed, thanks so much for all the bug reports as you try to package 0.13. I really appreciate it! Keep them coming; we'll get them fixed as soon as we can.

**Comment by reidpr** [comment]
As background, the `vX.Y.tar.gz` tarballs are produced by GitHub and we can't change them or remove them. They are simply a tarball of the corresponding Git tag, and as such require bootstrapping with `autogen.sh` like a Git checkout. We would prefer not to offer them, frankly, because they confuse users (though now I'm less certain because they provided an useful check here!). In contrast, `charliecloud-X.Y.tar.gz` are the output of `make dist` and added manually by us.

I examined the differences between the two linked tarballs with:
```
$ diff -u <(cd v0.13 && ls -1aR .) <(cd charliecloud-0.13 && ls -1aR .)
```
and found the following:

* Erroneous omissions in `charliecloud-0.13.tar.gz` vs. `v0.13.tar.gz` (and the Git source):
  * `autogen.sh`; end-users probably should be able to bootstrap `configure`.
  *  `bin/ch-tar2squash`, as reported.
  *  `doc/man/README`, which contains instructions on how to read local man pages.
* Legitimate omissions:
  * `test/unused`; this directory contains two test programs that we haven't used in quite a while. Probably they should just be deleted.
* Erroneous additions:
  * none that I could find
* Legitimate additions:
  * `configure`, several `Makefile.in`, and a bunch of other Autotools-related files. This is correct, because it means users don't need Autotools to build Charliecloud.

I will prepare a PR to add the three erroneous omissions. Please let me know of any mistakes I've made.
