### ISSUE TITLE
add FAQ about what to do if programs want to chown stuff

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#67]
For example, Matlab will try to chown `/dev/pts/0` to `$USER:tty` if it's not group `tty` already, which barfs, even if the device can be accessed just fine. The workaround is to invoke `ch-run` with `-g 5` or whatever GID `tty` has.

**Comment by olifre** [comment]
I'm a bit confused as on how the workaround works (but am interested in it, since this might also help a user-privileged `sshd` to actually run inside a user namespace container). 

Doesn't starting the user namespace map only the invoking user's uid / gid to a selectable uid / gid in the container (since the kernel only allows to map a single uid / gid pair)? If so, wouldn't this mean the approach only works if the invoking user's group matches the group owning `/dev/pts/0` on the host already?

Starting a container with `-g 5` with `tty` being group `5`, and myself being a user with uid and gid `38503`, I see:
```
$ ls -lan /dev/pts
total 0
drwxr-xr-x.  2 65534 65534      0 Nov  6 08:36 .
drwxr-xr-x. 18 65534 65534   2860 Nov  6 08:37 ..
crw--w----.  1 65534 65534 136, 0 Nov  9 19:59 0
crw--w----.  1 65534 65534 136, 1 Nov  9 20:07 1
c---------.  1 65534 65534   5, 2 Nov  6 08:36 ptmx
```
Am I missing something obvious?

**Comment by reidpr** [comment]
I'm a little fuzzy on this situation myself because it's been a while, but I think it may be the following. Note that this is all completely unnecessary; MATLAB has no reason to do this.

Assume the user has EUID of 1000 and EGID of 1001 and `/dev/pts/0` is the relevant PTY file owned `1000:5`.

1. MATLAB `stat(2)`s `/dev/pts/0` and checks the GID.
2. This GID is `nogroup` (65534) because `tty` (5) on the host side isn't mapped (and can't be for unprivileged user namespaces).
3. MATLAB concludes this is bad.
4. MATLAB executes `chown("/dev/pts/0", 1000, 5)`.
5. This fails because GID 5 on the container side is not mapped.
6. MATLAB pukes.

By mapping GID 1001:5 (instead of the default 1001:1001), step 4 succeeds because GID 5 is now mapped, i.e. the call is mapped to `chown("/dev/pts/0", 1000, 1001)`, and MATLAB is happy.

**Comment by olifre** [comment]
Understood! Many thanks for the explanation. 

Yes, with sshd this will not help to much, sadly. But in any case, I think the main usecase for sshd in a user namespace container (to be used with HTCondor for connection to running jobs) should be replaced by launching the sshd on the host on which tje job is running, and then calling `nsenter` from the sshd (e.g. via `authorized_keys`). But I still need to convince HTCondor upstream about that, it seems they were under the impression that privileges are required to call `nsenter` (which is of course untrue for user namespace containers). 

So for now, our workaround sadly is to use privileged containers until HTCondor is fixed. 
Since some of our users also start to use MATLAB, though, I will certainly keep this in mind! Thanks!

**Comment by reidpr** [comment]
> nsenter from the sshd

This would work; an alternative is that Charliecloud containers can talk to each other just fine, so you can start a new container with the same image and it will work too.

**Comment by olifre** [comment]
> an alternative is that Charliecloud containers can talk to each other just fine

Yes - this would indeed be another technique to modify the HTCondor code. 
I'll have a look at that myself maybe if there's no reply by the HTCondor people in due time, and after I'm finished with the Charliecloud plugin for HTCondor of course. 
Thanks for the ideas!

**Comment by olifre** [comment]
For those who are interested in running sshd inside a user namespace (e.g. since HTCondor does that for interactive jobs and `condor_ssh_to_job` at the moment), I tested it works fine using the `-g 5` workaround. 
In any case, I've also opened an OpenSSH bug report including a patch to OpenSSH here:
https://bugzilla.mindrot.org/show_bug.cgi?id=2813

**Comment by reidpr** [comment]
> sshd in a user namespace container [...] should be replaced by launching the sshd on the host on which tje job is running, and then calling nsenter from the sshd

@olifre, would the new `--join` argument help here?

**Comment by olifre** [comment]
> @olifre, would the new --join argument help here?

Yes, certainly. Sadly, the way the HTCondor code is structured, this is not easy to add (they just wrap the container runtime command around every command). So it's also a structural bug on that end. 
But certainly, using `nsenter` or `--join` would be the correct approach here. When I get the chance (hopefully later this year at the HTCondor workshop) I'll suggest it. Thanks for the hint! :+1:

**Comment by olifre** [comment]
@reidpr For `sshd`, as discussed in https://bugzilla.mindrot.org/show_bug.cgi?id=2813 right now, it seems that removing `tty` from `/etc/group` in the container helps to prevent the `chown`. Do you think it's also worthwhile to document that?

**Comment by reidpr** [comment]
Hmm, good point. Let's discuss over in #298.
