### ISSUE TITLE
ch-test: don't delete image directories before knowing if we can proceed

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#672]
@Brofessional reports offline:

> If you run `ch-test` with no arguments, it tries to run all the phases. Including a phase where it removes and creates your tar dir. This may be the desired outcome on your laptop. But on [our cluster] it `rm`d my full scope build full of images leaving me to [...] retransfer back to the cluster. So for cluster testing this has been a pretty big setback.

Example output:

```
$ ./bin/ch-test
ch-run:       /users/rgoff/charliecloud-0.14~pre+chtest2.81040d1/bin/ch-run
bats:         /users/rgoff/[...]/libexec/bats (0.4.0)
tests:        /users/rgoff/charliecloud-0.14~pre+chtest2.81040d1/test
installed:    no
git workdir:  no
contributor:  yes; rgoff@lanl.gov in README.rst

phase:                build run examples
scope:                standard (default)
builder:              docker (environment)
pedantic mode:        yes (default)
use generic sudo:     no (default)
unpacked images dir:  /users/rgoff/img (environment)
packed images dir:    [...]/rgoff/tarballs (environment)
fs permissions dirs:  skip (environment)

ch-test version: 0.14~pre+chtest2.81040d1
warning: inconsistent source version: 0.14~pre

checking namespaces ...
ok

removing [...]/rgoff/tarballs
creating [...]/rgoff/tarballs

removing /users/rgoff/img
creating /users/rgoff/img

checking builder ...
error: builder: docker: not installed
```

In this specific case, the `build` phase couldn't be done because there is not builder installed, but `ch-test` deleted `$CH_TEST_TARDIR` before figuring that out.

`ch-test` shouldn't do any deleting until it's fairly confident it can get through all the requested tests.

**Comment by j-ogas** [comment]
During an offline meeting we discussed the following options:

1. Remove default `phase=all` behavior and instead require users to specify a phase;
2. sanity check, e.g., see if we can rebuild what we are deleting, or detect if we are on a cluster;
3. use `$TMP_` for creating image artifiacts and then move to `CH_TEST_[TAR|IMG]DIR`;
4. use one or more sub directories; and
5. do nothing.

I prefer option one (1). Users should specify either `build`, `run`, `examples`, or `all`; otherwise print `usage`. This is, IMO, the simplest to implement and most intuitive usage solution.
