### ISSUE TITLE
completely remove skopeo and umoci support?

### ISSUE THREAD

**Issue by reidpr** [hpc/charliecloud#675]
With the merge of PR #616, we no longer use skopeo or umoci for any wrapped functionality. This leaves a few demo scripts that we do support in the test suite. Do we want to keep supporting these?

A partial measure would be to document these tools' use in the FAQ or something but not support it in the test suite.

**Comment by rstyd** [comment]
I believe we should. We had the Build.skopeo_umoci test before ch-grow existed because users had expressed interest in using them. I'm not sure if ch-tug is a complete replacement since it's only able to pull from dockerhub at the moment. 

A secondary question is: are we going merge #593 or should it be updated to use ch-tug instead?

**Comment by reidpr** [comment]
Discussion: We'll do this.
