### ISSUE TITLE
ch-tug: man page not installed

### ISSUE THREAD

**Issue by wiene** [hpc/charliecloud#681]
In version 0.14 the `ch-tug` man page is built but not installed.

**Comment by reidpr** [comment]
Good catch yet again. Sorry about that!

@heasterday, in addition to fixing `doc/Makefile.am`, perhaps you could look a little at why `docs-sane` didn't catch it? I would have expected it to fail the install-mode Travis tests.

**Comment by heasterday** [comment]
@reidpr Looks like the install [tests skip](https://travis-ci.org/hpc/charliecloud/jobs/658909463#L1319) running `docs-sane` since the documentation source isn't present at this stage. 

One option I can think of to catch this issue is to add logic to `docs-sane` to check if it's being called in a source dir versus an install dir and check a subset of things in the latter (like do the man pages have a corresponding binary). Thoughts?

**Comment by reidpr** [comment]
OK. I think the test as well as `docs-sane` have a number of assumptions about where the documentation is that are not met when installed. I don't know how hard those would be to fix.

I think simply installing `ch-tug.1` (a one-liner) and fixing `docs-sane` along with its test (harder) should be done separately. Can you split the latter into a new issue?
