### ISSUE TITLE
configure: fails checking for asprintf(3) under Clang

### ISSUE THREAD

**Issue by olifre** [hpc/charliecloud#798]
As found in:
https://bugs.gentoo.org/732214
configure tests fail with clang, since clang has `-Wformat` as part of `-Wall`, and the check testing for `asprintf` complains with a format warning, which becomes an error due to `-Werror`:
```
configure:4946: checking for asprintf
configure:4946: x86_64-pc-linux-gnu-clang -o conftest -O2 -pipe -march=native -frecord-gcc-switches -fno-diagnostics-color -std=c99 -Wpedantic -Wall -Werror  -Wl,-O1 -Wl,--as-needed -fuse-ld=lld -Wl,--defsym=__gentoo_check_ldflags__=0 conftest.c  >&5
conftest.c:46:18: error: format string missing [-Werror,-Wformat]
return asprintf ();
       ~~~~~~~~  ^
1 error generated.
[...]
| int
| main ()
| {
| return asprintf ();
|   ;
|   return 0;
| }
configure:4946: result: no
configure:4954: error: asprintf() not found. Please report this bug.
```
I'm not sure how to best fix this (I'm not an autotools expert), probably dropping `-Werror` for the test or using `-Wno-error=format` might be easiest, or using a different test for `printf`-like functions which uses a dummy format string.

**Comment by junghans** [comment]
Over the years I have patched `-Werror` out of some many packages, I personally like to run all the CI with `-Werror`, but don't inject in by default.

**Comment by reidpr** [comment]
Thanks Oliver and Christoph!

The general principle I like is to have diagnostics that are as noisy as practical. That's the reason we do `-Wall -Werror`.

As for the `asprintf(3)` test, IMO that's definitely a broken test. The format string isn't optional. I think that it's indeed our fault; we do not seem to instruct Autoconf to use an argument:

https://github.com/hpc/charliecloud/blob/254fa07a2241ea0349179ea42471b1abdefafeea/configure.ac#L158

I'm not sure exactly how to fix it, as a quick look at the `AC_CHECK_FUNC` documentation doesn't say anything about function arguments.

Let's have the focus of this issue be fixing that test.

As for `-Werror` generally, I would be very open to a PR that added an argument to `configure` that replaced or extended `-Werror`, or otherwise cleaned up how we deal with `CFLAGS`. E.g., in this case it could be `-Wno-error=format`. This should be changeable more easily than a patch.

I'm disinclined to do `-Werror` except for CI — e.g., we would have missed this buggy test if that were the case. I would like to have it in there by default, to be disabled if specific problems arise. I am nervous about leaving it out of the Gentoo package indefinitely.

**Comment by junghans** [comment]
openSUSE has a similar policy https://en.opensuse.org/openSUSE:Specfile_guidelines#Werror and the Gentoo's rational is quite reasonable: https://devmanual.gentoo.org/ebuild-writing/common-mistakes/index.html.

**Comment by junghans** [comment]
How about #799?

**Comment by reidpr** [comment]
Christoph, thanks for the additional links! From the second:

> breaks without purpose
> random breakage

I disagree. IMO, this breakage identifies real problems in our code, e.g. as happened here. It isn't meaningless.

> Turning off "-Werror" we will still see the warnings

I'm skeptical this will occur in practice. In my view, based on my human factors training, what is more likely is that new warnings that still yield a successful build will not be noticed. Even if a given distro/downstream has processes that ensure new warnings are seen and considered (is this true for OpenSUSE and Gentoo?), that leaves all the rest.

Thanks for the PR thought! I'll comment on it.

**Comment by reidpr** [comment]
Closing because PR #800 fixes this issue as described. PR #799 will stand alone.
