### ISSUE TITLE
can't "yum install sudo" interactively in a ch-run container, even with -u 0

### ISSUE THREAD

**Issue by aruhela** [hpc/charliecloud#928]
This might be a trivial question.

I was trying to install a library inside charliecloud container that requires root access.  I ran my centos 8 containers with " ch-run -u 0 -w  mycontainer -- bash " but seeing an issue in installing any library in it. 

An example is attached for reference. Any suggestions?
[root.txt](https://github.com/hpc/charliecloud/files/5694752/root.txt)

**Comment by reidpr** [comment]
Hello Amit, not trivial at all; in fact you've run into a rather deep issue relevant to all fully-unprivileged containers. Thank you for the fine example.

I'm pretty sure what is happening is that `yum` is expecting some privileged system call to succeed (because it believes it's root). The error doesn't say specifically what failed, unfortunately.

The good news is that we have a pretty good understanding of what's going on, and we've implemented a workaround, though in the context of building Dockerfiles. [More details in that context.](https://hpc.github.io/charliecloud/command-usage.html#quirks-of-a-fully-unprivileged-build) (Note, these docs will be significantly improved in 0.21, expected in a few days.) If you are running 0.20 and put `RUN yum install sudo` in a Dockerfile, `ch-grow` will apply the workarounds automatically; in 0.21 you will need to say `ch-image build --force` but it will warn you if the build fails and it things `--force` will help. (`ch-grow` is becoming `ch-image` in 0.21.)

If you prefer to install that package interactively (aside, we do discourage this), you can install the `fakeroot` package from EPEL and then say `fakeroot yum install sudo`.

One final aside, I suspect `sudo` will have problems as well, since manipulating users in an unprivileged container will run into related issues. Happy to have that discussion too so we can improve our guidance (probably best in a separate issue).

**Comment by aruhela** [comment]
Thanks, Reid for the great explanation and workarounds,

Let me try your suggestions and report to you my findings.

**Comment by aruhela** [comment]
Hi Reid,

I upgraded Charliecloud on both VM as well as target cluster to 0.22~pre+8e65fec. I generated a centos8 image by adding "RUN yum -y install sudo" to the Docker specification file.

I run the container with "ch-run -u 0 -g 0 -w centos8  -- bash" command and was able to install test packages like vim or make without any issue.  

I believe the issue is resolved. You may close the issue.

Thanks again for the help and good work on the latest versions.

**Comment by reidpr** [comment]
Fantastic! Please let us know of any further problems. Closing per your request.
