### ISSUE TITLE
charliecloud installs stuff in /usr/libexec

### ISSUE THREAD

**Issue by lnussbaum** [hpc/charliecloud#93]
Hi,

/usr/libexec is not a standard directory in the Filesystem Hierarchy Standard.

I would recommend moving those files to /usr/lib/charliecloud.
See http://www.pathname.com/fhs/pub/fhs-2.3.html#USRLIBLIBRARIESFORPROGRAMMINGANDPA

(I ran into this while prepare a Debian package for charliecloud -- Debian's linter (lintian) noticed this)

**Comment by olifre** [comment]
Hi!

Yes, the problem is that `/usr/libexec` is commonly used on most distros which are not Debian (e.g. RedHat, Gentoo). They follow the optional extension to FHS 3.0 (using `/usr/libexec` for executables, and keeping `/usr/lib` reserved to libraries):
http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html


However, since I have also encountered this when creating a Debian package, there's already a flag to change things! 

You may want to look at:
https://github.com/hpc/charliecloud/pull/92
It contains Debian packaging, and installs things to the paths preferred on Debian. 
Note this also contains a `charliecloud-doc` package which installs the sphinx-documentation (and patches it such that `lintian` is happy). Since I'm not a Debian expert, this may not be the best packaging, but maybe you can take it and improve it? Is your goal to get it into Debian proper, or is that for a custom build? If it's for a custom build, you may also want to look at https://build.opensuse.org/project/show/home:ubn:charliecloud . 

Manpages (another thing the Linter will complain about) are also in planning:
https://github.com/hpc/charliecloud/issues/82

**Comment by lnussbaum** [comment]
oh, nice!

my goal is an official debian package. My work (in progress) is at https://anonscm.debian.org/cgit/debian-science/packages/charliecloud.git

I'll merge your changes.

By any chance, are you interested in co-maintaining the package in Debian? It would mostly be about watching the package for bugs etc.

**Comment by olifre** [comment]
> I'll merge your changes.

Nice, many thanks! 
It might also be interesting (in the long term), to update the packaging code inside the charliecloud-tree to reflect the more polished version then. Even though we then have a real Debian package, it would be nice to keep the duplicate code in the charliecloud repo, so it can undergo testing (I added basic `travis` scripting to check the package still builds for git master and any PR - it also runs `lintian` afterwards). 
This allows to catch things like #85 (which looks like a sensible idea at first, but breaks packaging) before they enter the charliecloud code. 


> By any chance, are you interested in co-maintaining the package in Debian? It would mostly be about watching the package for bugs etc.

I think I can offer you a better solution. I'm myself not a daily user of Debian (I use Gentoo and administrate mostly CentOS / Ubuntu), but my colleague @wiene is a daily full-time Debian user, is also interested in following charliecloud and will certainly notice issues earlier. I gave him a personal ping just a few moments ago (offices are close), he will let you know.

**Comment by wiene** [comment]
I would be happy to lend a helping hand in co-maintaining the Debian package.

**Comment by reidpr** [comment]
FWIW your BDFL uses Debian on any Linux box where he gets to choose, and my home box hasn't been reinstalled (upgrades only) since 1998. My dev box for Charliecloud is a Stretch VM. So, I'm particularly excited to hear of the possibility of a Debian package and very interested in supporting the effort (along with other distros, of course, but Debian is particularly close to my heart).

Regarding logistics:

1. Is the consensus here in this issue that the build parameter is sufficient and this issue can be closed?
2. Once things settle, could someone submit here issue(s), documentation PR(s), etc. pointing to Debian packaging info so that anyone who's interested can find out the status and who's responsible?

Thanks,
Reid

**Comment by reidpr** [comment]
For example, if someone files a WNPP bug in Debian, please also file a corresponding issue here.

**Comment by lnussbaum** [comment]
Hi,
Yes, the build parameter is enough. I've opened https://github.com/hpc/charliecloud/issues/95 to track the work on the debian package. So, I'm closing this issue. Thanks!
