### ISSUE TITLE
build fails, cannot find base.sh

### ISSUE THREAD

**Issue by agilly** [hpc/charliecloud#947]
Hello,

I followed the tarball install instructions:

```
wget https://github.com/hpc/charliecloud/releases/download/v0.21/charliecloud-0.21.tar.gz
tar -xvzf charlie*gz
cd charliecloud-0.21
./configure
make
sudo make install
```

Then I created the example docker file with a centos base from the install docs. When I try to build, I get:
```
$> ch-build -t hello .
/usr/local/bin/ch-build: line 4: /usr/local/bin/../lib/charliecloud/base.sh: No such file or directory
```

There seems to be something wrong with paths, links and permissions in general, as an example I cannot run the example since `cd /usr/local/share/doc/charliecloud/examples/hello` throws a permission error.

My OS is OpenSuse 15 and my shell is bash. The full install logs can be found at [https://pastebin.pl/view/6d63e8d3](https://pastebin.pl/view/6d63e8d3).

I also tried pulling directly from the repo and using autoconf, it fails with the same result.

**Comment by reidpr** [comment]
Hi Arthur, I'm sorry for the trouble and we really appreciate the bug report.

Your logs link times out for me — can you try a different pastebin? I believe GitHub Gists have worked for us in the past.

That said, something is definitely wrong with permissions in `sudo make install`:

```
$ rm -Rf /tmp/foo
$ ./configure --prefix=/tmp/foo
$ make
$ sudo make install
$ /tmp/foo/bin/ch-build --help
-bash: /tmp/foo/bin/ch-build: Permission denied
$ ls -ld /tmp/foo
drwxr-x--- 6 root root 4096 Jan  5 10:57 /tmp/foo
```

This happens in 0.20 as well.

As a workaround, you can probably patch up the permissions manually, maybe with something like `chmod o+rX`?

Again I really appreciate your pointing this out! We will get it fixed ASAP.

**Comment by reidpr** [comment]
Appears to be umask related, so better workaround: set your umask to something permissive, e.g. 0022, then `sudo make install`.

**Comment by agilly** [comment]
Hi @reidpr, thanks for being so reactive! Unfortunately neither checking out the `umask_947` branch, neither setting `umask 0022` helps, I still get the same message.

Please find the logs below, hopefully it will work this time: [https://pastebin.ubuntu.com/p/SdbpR6mpx4/](https://pastebin.ubuntu.com/p/SdbpR6mpx4/)

**Comment by reidpr** [comment]
Thanks for the logs @agilly; I can see them this time. And again I really appreciate you pointing out the bug!

I wonder if you have leftover bad permissions in `/usr/local` from your previous buggy install.

Can you try the following sequence of commands for me and make a pastebin of the results?

```
$ cd /tmp
$ git clone https://github.com/hpc/charliecloud
$ cd charliecloud
$ git checkout master
$ ./autogen.sh && ./configure --prefix=/tmp/foo
$ make
$ sudo sh -c 'umask && make install'
$ sudo ls -ld /tmp/foo
$ sudo ls -lR /tmp/foo

$ cd /tmp
$ sudo rm -Rf charliecloud
$ git clone https://github.com/hpc/charliecloud
$ cd charliecloud
$ git checkout master
$ ./autogen.sh && ./configure --prefix=/tmp/bar
$ make
$ sudo sh -c 'umask 0022 && umask && make install'
$ sudo ls -ld /tmp/bar
$ sudo ls -lR /tmp/bar

$ cd /tmp
$ sudo rm -Rf charliecloud
$ git clone https://github.com/hpc/charliecloud
$ cd charliecloud
$ git checkout umask_247
$ ./autogen.sh && ./configure --prefix=/tmp/baz
$ make
$ sudo sh -c 'umask && make install'
$ sudo ls -ld /tmp/baz
$ sudo ls -lR /tmp/baz
```

Incidentally, if you're not aware, GNU Stow is (IMO) a really nice way to keep `/usr/local` organized.

**Comment by agilly** [comment]
Cheers @reidpr, please find the logs for the above at :  [https://pastebin.ubuntu.com/p/8cNPC434Sd/](https://pastebin.ubuntu.com/p/8cNPC434Sd/).

I was not aware of Stow, in general we try to keep `/` very minimal, with just build tools and container software. We use docker for admin-requiring services and singularity for user stuff. Now we are bridging to a new infrastructure that does not support Singularity, which is why I am tring Charliecloud out.

**Comment by reidpr** [comment]
Hello @agilly, thanks for the information and your patience.

It turns out there are TWO things going wrong for you. The first is (I suspect) the bad permissions bug, though see below. The second is that it's putting the shell and Python libraries into `$PREFIX/lib64` instead of `$PREFIX/lib`:

```
 /usr/bin/install -c -m 644 base.sh build.py charliecloud.py fakeroot.py misc.py pull.py push.py '/tmp/bar/lib64/charliecloud'
```

The second sounds familiar; I'll talk with my team about it. What distribution and architecture are you on?

As for the first thing, unfortunately I typo'ed the branch name and so the third install above just built the master branch again. Can you try the following. The changes are (1) fix branch typo; (2) tell `configure` to use `$PREFIX/lib`; and (3) add test command at the end.

```
$ cd /tmp
$ sudo rm -Rf charliecloud baz
$ git clone https://github.com/hpc/charliecloud
$ cd charliecloud
$ git checkout umask_947
$ ./autogen.sh && ./configure --prefix=/tmp/baz --libdir=/tmp/baz/lib
$ make
$ sudo sh -c 'umask && make install'
$ sudo ls -ld /tmp/baz
$ sudo ls -lR /tmp/baz
$ /tmp/baz/bin/ch-build --version
```

I recommend you run the commands one at a time so you can more easily catch any further errors I've made.

If it still doesn't work, perhaps we could schedule a video call and do some live debugging? In this case please e-mail me at reidpr@lanl.gov. I see you are located in Europe but I'm sure we can make something work. My time zone is currently US MST (UTC–7). I'll be here until ~6:00pm my time today and then again Monday.

As for GNU Stow, it would let you install with a prefix of e.g. `/usr/local/stow/charliecloud-0.21`; Stow then handles symlinking into normal paths in `/usr/local`. The main advantage for me is uninstalling/upgrading unruly software that doesn't implement `make uninstall` reliably (😬).

**Comment by agilly** [comment]
Hi @reidpr,
I think it's working. Please see the full log [here](https://pastebin.ubuntu.com/p/wvny2Cw288/).

I still have the problem that the previous broken install seems to have survived `make uninstall` and my attempts at overwriting with a new `make install` (I now see your point about Stow :D). Would you be able to share the required commands to perform a cleanup and clean install? I would assume that a final version would just require me to run the above without `--prefix` and `--libdir` to perform a working install of `umask_947`. I managed to avoid the previous error by running `./autogen.sh && ./configure --libdir=/usr/local/lib` followed by `make && make install`. But I am afraid there are some dangling consequences that I didn't think about...

(Although my workplace is located in Europe I am physically located in GMT+7, which makes it quite hard to schedule calls with the US... but if there's not other way I'm sure we can figure something out).

**Comment by reidpr** [comment]
Hello @gilly, great news!

I believe the persistent permissions problems are because (1) Autotools packages don't re-create directories that already exist or change metadata on them; (2) they also don't remove directories on uninstall IIRC; and (3) possibly other errors in the manual parts of our Makefiles.

I don't have a ready-to-go command for you, but it if it were me, I would start with `sudo make uninstall` and then `find /usr/local -type d -ls`. The latter will do an `ls -l` style listing of all directories in `/usr/local`. You could extend it to give a more targeted listing of only directories with specified permissions (`find(1)` has several predicates for this). Then you can use this list to either `chmod 755` the directories (or your preferred permissions), or remove them.

If that still doesn't work, if you feel comfortable paste-binning an `ls -lR /usr/local` I'd be happy to look at it.

**Comment by reidpr** [comment]
Closing this as a duplicate, since there are two separate problems. The umask stuff is resolved in PR #949, which I just merged. The libdir stuff is issue #683, which is still open.

@agilly, thanks for the bug report; it made Charliecloud better by resolving some long-standing problems. And please speak up if I've made a mistake by closing!

**Comment by ana** [comment]
Hi @agilly . If it helps, you should be able to get a working package of charliecloud 0.21 for opensuse at https://build.opensuse.org/package/show/network:cluster/charliecloud (see tab Repositories)

**Comment by agilly** [comment]
Thanks @reidpr I managed to uninstall and reinstall by manually `find`-ing the files as you suggested.

**Comment by reidpr** [comment]
Great, thanks for the update! If it helps, the PR mentioned above is in version 0.22, released yesterday.
