### ISSUE TITLE
official charliecloud package in Debian

### ISSUE THREAD

**Issue by lnussbaum** [hpc/charliecloud#95]
I'm opening this issue to track the creation of an official Debian package for charliecloud.

Success criterias:
* the package is accepted in Debian
* there are no open issues related to upstream
* we figure out how to properly collaborate together around the package's maintenance

Current status:
* I filed an ITP bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882259
* @wiene agreed to co-maintain
* I have basic packaging at https://anonscm.debian.org/cgit/debian-science/packages/charliecloud.git (so, under the umbrella of debian-science, that maintains other HPC-related packages)

Open questions:
* @wiene suggested we switch to dgit for package maintenance. no objections from me, even if I've never looked deeply into dgit (at least it will be a way to learn). @wiene, do you want to give it a first try?
* we should merge our packaging on top of https://github.com/hpc/charliecloud/pull/92 (probably it makes sense to wait until that pull request is accepted), so that we can have automated testing integrated with upstream's.
* the tarballs provided in https://github.com/hpc/charliecloud/releases do not include bats. However, a 'make export' in charliecloud's git does. How will future releases be generated? With or without bats? For the first upload to Debian, it makes sense to ship a git snapshot (unless a new release is made very soon). But I'd rather stick to what will be done in the future.

**Comment by wiene** [comment]
> @wiene suggested we switch to dgit for package maintenance. no objections from me, even if I've never looked deeply into dgit (at least it will be a way to learn). @wiene, do you want to give it a first try?

My proposal is available [here](https://github.com/wiene/charliecloud-deb). To build the packages, run
```
git deborig
dgit build
```
The contents is based on [this upstream commit](https://github.com/hpc/charliecloud/commit/3eb9e3edfbcd61257bb52a361cf01782fcf15b5d) and uses the packaging written by @lnussbaum which was taken from [Alioth](https://anonscm.debian.org/cgit/debian-science/packages/charliecloud.git). Three minor changes are included with respect to what is presently on Alioth:

1. The (empty) directory `test/bats` is removed. Otherwise `dgit build` complains:
```
dgit:  cannot represent change: not a plain file (000000->160000): test/bats
```
2. The bats copyright is removed from the the file `debian/copyright` because of item 1.
3. The `debian/changelog` file is adjusted.

Please check whether everything look reasonable to you.

> we should merge our packaging on top of #92 (probably it makes sense to wait until that pull request is accepted), so that we can have automated testing integrated with upstream's.

[This commit](https://github.com/wiene/charliecloud/commit/21bd741571653b5c53fe0583aafdad455702a917) merges the work of @lnussbaum and @olifre. After this patch, the contents of the `packaging/debian` directory in the upstream code will be almost identical to the `debian` directory in the Debian repository. The only remaining differences are:

1. `@VERSION@` is used in packaging/debian/changelog instead of a hardwired version
2. I added a line in `packaging/debian.sh` to make Travis happy:
```
ln -s ../charliecloud-${VERSION}.tar.gz charliecloud_${VERSION}.orig.tar.gz
```
This is required due to the change to the quilt format.

If this looks acceptable, maybe @olifre can include this patch in his PR.

**Comment by reidpr** [comment]
FWIW, version 0.2.3 should be out soon, so maybe that's a good one to package.

**Comment by lnussbaum** [comment]
Hi,

To move things forward a bit, I've uploaded a debian package for review by the team responsible for reviewing new packages. This usually takes a few weeks.

The packaging work now lives at https://salsa.debian.org/hpc-team/charliecloud (Debian's gitlab instance).

Once accepted, or in the meantime, we can continue to work on improving the package.

**Comment by wiene** [comment]
Thanks @lnussbaum. I have three questions concerning the status quo:

1. Is there a particular reason why you [increased the debhelper compat level to 11](https://salsa.debian.org/hpc-team/charliecloud/commit/73df68d0c137f6e6b77e13cf7048a307afc93780)? That is fine for the inclusion in Debian (i. e. sid) but it prevents builds for stretch (which is also nice to have).
2. bats is still included (see open question no. 3 in the first message of this issue). @reidpr, how do you plan to handle bats in future releases?
3. @lnussbaum, do you want to stick with pristine-tar? In this case I would delete [this repository](https://github.com/wiene/charliecloud-deb) to avoid confusion.

**Comment by lnussbaum** [comment]
Hi,

1. raising the compat level to 11 doesn't not prevent building in stretch: debhelper 11 is available in stretch-backports. So once charliecloud is in testing, we can provide an official backport for it.
1. well, I'm fine to changing to whatever upstream decides for future releases
1. my understanding of dgit so far is that it's hype but has little adoption so far. I haven't had time to look into it and to understand its pros/cons compared to the traditional workflow. have you found some material that does that?

**Comment by wiene** [comment]
1. You are right. I did not check backports.
2. Me, too. This was a question directed towards @reidpr.
3. You might be right. I am not sure myself which tool is more convenient in the long run. I accidentally stumbled across dgit in [this article](https://www.preining.info/blog/2014/06/debian-pristine-tar-packaging) whose contents seems to be outdated by now (judging from [the pristine-tar commit history](https://anonscm.debian.org/cgit/collab-maint/pristine-tar.git)). I do not know of any material comparing both workflows. All I know about dgit is from [the dgit-maint-merge man page](https://manpages.debian.org/stretch/dgit/dgit-maint-merge.7.en.html) and [the dgit man page](https://manpages.debian.org/stretch/dgit/dgit.1.en.html).

**Comment by reidpr** [comment]
> bats is still included (see open question no. 3 in the first message of this issue). @reidpr, how do you plan to handle bats in future releases?

Current master (and upcoming 0.2.3) will use the system Bats, so I'd recommend (or suggest?) that the package either `Recommends` or `Suggests` the package `bats`. Looking at the definitions in Chapter 7 of the Debian FAQ, I'd lean more towards `Recommends`, but I defer on that to those who know Debian better.

Probably you want to start from the Git tarball rather than `make export` because the latter is kind of a kludge.

As an aside, I'm back at work now so should be more responsive.

**Comment by wiene** [comment]
Those who are interested can follow the status of charliecloud in Debian on https://tracker.debian.org/pkg/charliecloud

**Comment by wiene** [comment]
Since in the meantime Charliecloud is both in Debian unstable and testing, this issue can be closed in my opinion.

**Comment by wiene** [comment]
@reidpr, is there still anything which prevents this issue from being closed?

**Comment by reidpr** [comment]
Sorry, lost track of the January 30 comment. Closing.
